import Head from "next/head";
import HomePageStyle from "../styles/pages/home.module.scss";
import Link from "next/link";
import Image from "next/image";
const Index = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={HomePageStyle.home}>
        <div className="home-wrap mb-5">
          <div className="home-wrap-left">
            <label className="mb-2">Wander The World</label>
            <h2 className="heading mb-2">From short breaks to long adventures.</h2>
            <p className="desc mb-3">
              Travel blog featuring travel tips, guides, and photography from
              around the world. Whether you need guidance for your first trip,
              or you're a seasoned traveler looking for destination inspiration,
              you've come to the right place!
            </p>
            <Link href="/blog" className="base-btn">
              Read our blog
            </Link>
          </div>
          <div className="home-wrap-right">
            <Link href="/blog">
              <Image
                alt="blog Image"
                height={412}
                width={568}
                src="/blog1.webp"
                className="blog-image"
              />
            </Link>
          </div>
        </div>
        <div className="home-wrap mb-5">
        <div className="home-wrap-right">
            <Link href="/blog">
              <Image
                alt="blog Image"
                height={302}
                width={608}
                src="/blog2.webp"
                className="blog-image"
              />
            </Link>
          </div>
          <div className="home-wrap-left">
            <label className="mb-2">About us</label>
            <h2 className="heading mb-2">Adventurers and Storytellers</h2>
            <p className="desc mb-3">
            Through our award-winning blog, we love to provide travelers with guidance and inspiration and connect them to meaningful experiences as they travel the world with curiosity!
            </p>
            <Link href="/blog" className="base-btn">
            Learn about us
            </Link>
          </div>
        </div>
      </section>
    </>
  );
};

export default Index;
